# Generated by Django 5.1.1 on 2024-10-09 19:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='Описание')),
                ('poster', models.CharField(blank=True, default='', max_length=257, verbose_name='Изображение')),
                ('external_id', models.IntegerField(verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('region', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Город')),
                ('link', models.CharField(max_length=64)),
                ('likes', models.PositiveIntegerField(verbose_name='Лайки')),
                ('dislikes', models.PositiveIntegerField(verbose_name='Дизлайки')),
                ('views', models.PositiveIntegerField(verbose_name='Просмотры')),
                ('is_work', models.BooleanField(default=True, verbose_name='Доступен')),
                ('complaints', models.PositiveIntegerField(verbose_name='Жалобы')),
                ('boost', models.PositiveIntegerField(verbose_name='Уровень буста')),
                ('end_boost_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Окончания всех бустов')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Статистика активности',
                'verbose_name_plural': 'Статистика активности',
            },
        ),
        migrations.CreateModel(
            name='SuperChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('external_id', models.IntegerField(verbose_name='ID')),
                ('subscribers_added', models.PositiveIntegerField(default=0, verbose_name='Пришло подписчиков')),
            ],
            options={
                'verbose_name': 'Рекламный каналы',
                'verbose_name_plural': 'Рекламные каналы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('region', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Город')),
                ('ref_people', models.PositiveIntegerField(verbose_name='Приведенно пользователей')),
                ('ref_code', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Код рефералки')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом')),
                ('is_subscription', models.BooleanField(default=False, verbose_name='Подписался ли пользователь на каналы-спосноры')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('messages_per_second', models.IntegerField(default=0, verbose_name='Количество вызовов в секунду')),
                ('ban_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Забанен во время: ')),
                ('is_ban', models.BooleanField(default=False, verbose_name='Забанен')),
            ],
            options={
                'verbose_name': 'Юзер_бота',
                'verbose_name_plural': 'Юзеры_бота',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='Содержание')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('is_complaint', models.BooleanField(default=False, verbose_name='Жалоба')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Комментарии', to='mainBot.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Оставил', to='mainBot.user')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Владелец', to='mainBot.user'),
        ),
    ]
