# Generated by Django 5.1.1 on 2024-10-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0002_user_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(default='error', max_length=20, verbose_name='Код рефералки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_people',
            field=models.PositiveIntegerField(default=0, verbose_name='Приведенно пользователей'),
        ),
    ]
