# Generated by Django 5.1.1 on 2024-10-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0003_alter_user_ref_code_alter_user_ref_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_people',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Приведенно пользователей'),
        ),
    ]
