# Generated by Django 5.1.1 on 2024-10-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0004_alter_user_ref_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='folowers',
            field=models.PositiveIntegerField(default=0, verbose_name='Фоловеров'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='external_id',
            field=models.BigIntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='external_id',
            field=models.PositiveBigIntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_people',
            field=models.PositiveIntegerField(default=0, verbose_name='Приведенно пользователей'),
        ),
    ]
