# Generated by Django 5.1.1 on 2024-10-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0006_remove_user_ban_time_remove_user_messages_per_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='user',
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ManyToManyField(related_name='Владелец', to='mainBot.user'),
        ),
    ]
