# Generated by Django 5.1.1 on 2024-12-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0007_remove_channel_user_channel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='СategoryComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория жалобы',
                'verbose_name_plural': 'Категория жалоб',
            },
        ),
        migrations.RemoveField(
            model_name='channel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_complaint',
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='Содержание')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Жалобы', to='mainBot.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пожаловлся', to='mainBot.user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Категория', to='mainBot.сategorycomplaint')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
