# Generated by Django 5.1.1 on 2024-12-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0008_сategorycomplaint_remove_channel_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='complaints',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='views',
        ),
        migrations.AlterField(
            model_name='channel',
            name='boost',
            field=models.PositiveIntegerField(default=0, verbose_name='Уровень буста'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
