# Generated by Django 5.1.1 on 2024-12-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0009_remove_channel_complaints_remove_channel_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='СategoryChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Хэштэг')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Хэштэг',
                'verbose_name_plural': 'Хэштэги',
            },
        ),
        migrations.AlterField(
            model_name='channel',
            name='user',
            field=models.ManyToManyField(related_name='Владельцы', to='mainBot.user'),
        ),
        migrations.AddField(
            model_name='channel',
            name='categories',
            field=models.ManyToManyField(related_name='channels', to='mainBot.сategorychannel'),
        ),
    ]
