# Generated by Django 5.1.1 on 2024-12-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0010_сategorychannel_alter_channel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='сategorychannel',
            name='code',
            field=models.CharField(default='', max_length=16, verbose_name='Краткий код'),
        ),
    ]
