# Generated by Django 5.1.1 on 2024-12-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0011_сategorychannel_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сategorychannel',
            name='code',
        ),
        migrations.AddField(
            model_name='user',
            name='end_premium',
            field=models.DateTimeField(default=None, null=True, verbose_name='Конец премиума'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
    ]
