# Generated by Django 5.1.1 on 2024-12-23 15:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0012_remove_сategorychannel_code_user_end_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Координаты'),
        ),
    ]
