# Generated by Django 5.1.1 on 2024-12-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0014_user_categories_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='text',
        ),
    ]
