# Generated by Django 5.1.1 on 2025-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0015_remove_complaint_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='poster',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Изображение'),
        ),
    ]
