# Generated by Django 5.1.1 on 2025-02-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0017_alter_channel_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
