# Generated by Django 5.1.1 on 2025-03-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBot', '0018_alter_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='user',
            field=models.ManyToManyField(related_name='channels', to='mainBot.user'),
        ),
    ]
